### PR TITLE
fails with both "flatten" and "nothing" on fluentd 0.12.22

### PR DESCRIPTION
**Pull request by mjourard**
Updated the method being called to comply with TextParser updates.

### CODE REVIEW

**Comment by mgartner** [comment]
Thanks for the contribution @mjourard! We no longer use or maintain this repository. If you're up for it, we're happy to include you as a contributor or transfer ownership of this repository to your account.

**Comment by mjourard** [comment]
Ya sure, I can become a contributor/take over if you'd like

**Comment by mgartner** [comment]
@mjourard since you already have a fork and because this is in an organization I can't transfer it. I'll just mark this repo as no longer supported and add a link to your repo from the README here.

**Comment by mgartner** [comment]
@mjourard done. Thanks!

**Comment by mgartner** [comment]
@mjourard if you could send your email used for your ruby gems account I can add you as an owner of the gem.

**Comment by mjourard** [comment]
sure thing, it's mjourard@gmail.com

**Comment by mgartner** [comment]
I've added you as an owner. Thanks again @mjourard!

**Pull request closed without merging**
